[package]
name = "tx-fuzz"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tx-fuzz"
path = "cli/main.rs"

[dependencies]
engine = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }