[package]
name = "rakoon"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
[[bin]]
name = "rakoon"
path = "cli/main.rs"

[dependencies]
crossterm = { workspace = true }
ratatui = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
tokio-util = { workspace = true }
alloy = { workspace = true }

app = { path = "../crates/app" }
common = { path = "../crates/common" }
al = { path = "../crates/al" }
blob = { path = "../crates/blob" }
eip1559 = { path = "../crates/eip1559" }
eip7702 = { path = "../crates/eip7702" }
legacy = { path = "../crates/legacy" }
random = { path = "../crates/random" }
