[package]
name = "rakoon"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
[[bin]]
name = "rakoon"
path = "cli/main.rs"

[dependencies]
crossterm = { workspace = true }
ratatui = { workspace = true }
tokio = { workspace = true }

app = { path = "../crates/app" }
common = { path = "../crates/common" }