[package]
name = "legacy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
common = { path = "../common" }
tokio-util = { workspace = true }
alloy = { workspace = true }