[package]
name = "engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
alloy = { workspace = true }
rand = { workspace = true }

common = { path = "../common" }
mutator = { path = "../mutator" }